# pre-commit run --all-files
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
            args: [--markdown-linebreak-ext=md]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.15.0
      hooks:
          - id: mypy
            args: [--ignore-missing-imports]
    - repo: https://github.com/PyCQA/isort
      rev: 6.0.1
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 25.1.0
      hooks:
          - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 7.2.0
      hooks:
          - id: flake8
            additional_dependencies:
                - pep8-naming~=0.13.3
                - flake8-annotations~=3.1.1
                - flake8-assert-msg~=1.1.1
                - flake8-bugbear~=24.12.12
                - flake8-builtins~=2.5.0
                - flake8-comprehensions~=3.16.0
                - flake8-eradicate~=1.5.0
                - flake8-executable~=2.1.3
                - flake8-implicit-str-concat~=0.5.0
                - flake8-isort~=6.1.2
                - flake8-plugin-utils==1.3.3
                - flake8-pytest-style~=2.1.0
                - flake8-raise~=0.0.5
                - flake8-string-format~=0.3.0
