name: Release & publish
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
      - name: Build wheels and source tarball
        run: >-
          python -m build
      - name: Save dist packages
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download dist packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create a GitHub release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download dist packages
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create GitHub Release
        id: create_release
        run: gh release create ${{github.ref_name}} dist/* --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
